---
name: Build

on:
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - "**.md"
      - "LICENSE"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - "amd64"
          - "arm64"
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        env:
          GOARCH: ${{ matrix.arch }}
        run: |
          make build
